steps:
  # 步驟 1: 安裝專案依賴套件
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # 步驟 2: 執行 build 指令，產生靜態檔案
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # 步驟 3: 將 dist/ 目錄下的檔案同步到 Cloud Storage
  # 使用 -x 選項排除特定資料夾，避免刪除手動上傳的檔案
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gsutil'
    args:
      - '-m'
      - 'rsync'
      - '-d'
      - '-r'
      - '-x'
      - '素材/.*'  # 排除素材資料夾
      - '-x' 
      - 'logo/.*' # 排除logo資料夾
      - 'dist/'
      - 'gs://${_BUCKET_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUCKET_NAME: checkpoint_frontend